dist: trusty
sudo: true

addons:
  apt:
    packages:
    - libyajl-dev
    - libgeoip-dev
    - liblmdb-dev

env:
  - VER_NGINX=1.11.10
  - VER_NGINX=1.10.3

before_script:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - git clone https://github.com/SpiderLabs/ModSecurity.git
  - cd ModSecurity
  - git checkout v3/master
  - git submodule init
  - git submodule update
  - ./build.sh
  - ./configure --without-lmdb
  - make
  - sudo make install
  - cd -
  - git clone https://github.com/SpiderLabs/ModSecurity-nginx.git
  - wget "http://nginx.org/download/nginx-${VER_NGINX}.tar.gz" && tar -xf "nginx-${VER_NGINX}.tar.gz"
  - cd "./nginx-${VER_NGINX}"
  - ./configure --add-module=../ModSecurity-nginx
  - make
  - sudo make install
  - cd -
  - export PATH=$PATH:/usr/local/nginx/sbin
  - wget http://hg.nginx.org/nginx-tests/archive/tip.tar.gz
  - tar xvzf tip.tar.gz
  - cd nginx-tests-*
  - cp ../ModSecurity-nginx/tests/* .
  - export TEST_NGINX_BINARY=/usr/local/nginx/sbin/nginx

script:
    - prove .
